name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:        # permite disparo manual no GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    ## 🌟 Variáveis de ambiente válidas para TODO o job
    ## (precisam existir porque o schema Zod valida no bootstrap)
    env:
      # --- Banco de Dados ---
      DB_HOST: 127.0.0.1        # localhost, pois o runner acessa o service pelo host
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""           # senha vazia, combinando com MYSQL_ALLOW_EMPTY_PASSWORD
      DB_NAME: bot_whatsapp

      # --- OpenAI (valores fictícios) ---
      OPENAI_KEY: dummy-openai-key
      OPENAI_MODEL: gpt-3.5-turbo
      OPENAI_TEMPERATURE: 0.7

      # --- Twilio (valores fictícios) ---
      TWILIO_ACCOUNT_SID: dummy-sid
      TWILIO_AUTH_TOKEN: dummy-token
      TWILIO_WHATSAPP_NUMBER_FROM: whatsapp:+14155238886
      TWILIO_WHATSAPP_NUMBER_TO:   whatsapp:+5511999999999

      # --- Webhook ---
      WHATSAPP_VERIFY_TOKEN: dummy-token

      # --- Outros ---
      RATE_LIMIT_POINTS: 5
      RATE_LIMIT_DURATION: 60
      LOG_LEVEL: info
      NODE_ENV: test            # garante modo de teste

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: bot_whatsapp
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 5s
          --health-timeout 30s
          --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js e cache de dependências
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Instalar dependências
        run: npm ci

      - name: Compilar TypeScript
        run: npm run build

      - name: Lint (sem warnings)
        run: npm run lint -- --max-warnings=0

      - name: Executar testes
        run: npm test

      # - name: Upload cobertura
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage-report
      #     path: coverage
